# Dependencies
markdown:         kramdown
highlighter:      true
plugins:             [jekyll-paginate]

# Permalinks
permalink:        none

# Setup
title:            code.Oliver
tagline:          'Notes, tinkerings, experiments'
url:              https://soliveras.com/
paginate:         3
paginate_path:    "blog/page:num"
excerpt_separator: "<!--more-->"
baseurl:          /
highlighter:      rouge
author:
  name:          Oliver Sumo
  url:            https://soliveras.com
  email:          solivera2g3@gmail.com
  twitter:        solivera2g3

# Custom vars
github:
  repo:           https://github.com/dsolivera/soliveras.com.git
blog_masthead_pages:       
  About:          '/about'
  Projects:       '/projects'
  Resume:         '/resume'
personal_external_links:
  linkedin:        'https://www.linkedin.com/in/solivera/'
  twitter:         'https://twitter.com/solivera2g3'
  github:          'https://github.com/dsolivera'
